# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://tangx.in
date_format: "ordinal"
title: aloha.Mr.Tang
subtitle: "Pick it up, then write it down."
description: "Pick it up, then write it down."
keywords: 
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Mr.Tangx
# organization: 
# organization_url: 
github_username: octowhale
location: Chengdu, China
email: mr@tangx.in

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: octowhale/octowhale.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: octowhale
    repo: blog_comments
    oauth:
        client_id: 4688e20802279b78b427
        client_secret: 52f2c647d6c75fcc8991a2ff72cb70e4bdd1b6c5
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: octowhale
    repo: blog_comments
    clientID: 4688e20802279b78b427
    clientSecret: 52f2c647d6c75fcc8991a2ff72cb70e4bdd1b6c5
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-81140654-1

