# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://tangx.in
date_format: "ordinal"
title: aloha.Mr.Tang
subtitle: "Dev friendly with Sec and Ops"
description: "Pick it up, then write it down."
keywords: 
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Mr.Tangx
# organization: 
# organization_url: 
github_username: tangx
location: Chengdu, China
email: mr@tangx.in

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /topic/
    label: 专栏

  # -
  #   href: /wiki/
  #   label: 维基

  -
    href: /links/
    label: 链接


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
# permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    # wiki:
    #     output: true
    #     permalink: /wiki/:path/
    topic:
        output: true
        permalink: /topic/:path/

repository: tangx/tangx.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# !!!注意!!! gitment 和 gitalk 中的 repo
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: tangx
    repo: tangx.github.io
    oauth:
        client_id: 4688e20802279b78b427
        client_secret: 52f2c647d6c75fcc8991a2ff72cb70e4bdd1b6c5
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: tangx
    repo: tangx.github.io
    clientID: 4688e20802279b78b427
    clientSecret: 52f2c647d6c75fcc8991a2ff72cb70e4bdd1b6c5
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-81140654-1

